apiVersion: v1
kind: Service
metadata:
  name: pacman-port-fowarding
  namespace: pacman
spec:
  selector:
    app: pacman-v2.0
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP