apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: test1
  labels:
    app: busybox-v1.0
spec:
  replicas: 12
  selector:
    matchLabels:
      app: busybox-v1.0
  template:
    metadata:
      labels:
        app: busybox-v1.0
    spec:
      containers:
      - name: busybox-v1
        image: busybox
        # command: ["/bin/bash"] # This has a different default depending on image 
        args: ["sleep", "1d"]
        ports:
        - containerPort: 100
