apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
  namespace: pacman
  labels:
    app: pacman-v2.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pacman-v2.0
  template:
    metadata:
      labels:
        app: pacman-v2.0
    spec:
      containers:
      - name: pacman 
        image: ghcr.io/manu-07-ela/pacman:2.0 
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "1m"

